name: "Node Code Formatter"
description: "Formats your code automatically using your choosen formatters! No configuration - it just works."
author: "MarvinJWendt"
branding:
  icon: award
  color: orange
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
